### ISSUE TITLE
Windows Pre-Requisites : Rancher Desktop instead of Docker Desktop

### ISSUE THREAD

**Issue by mattisking** [Azure/azure-service-bus-emulator-installer#16]
We can't use Docker Desktop at work anymore (haven't been able to for a long time now). I can, however, install WSL, and I can use Rancher Desktop. Before going through this on my work laptop, does anyone happen to know for sure that Rancher wouldn't work?

Rancher can be configured to use Moby/dockerd and does itself require WSL on Windows for this purpose. Just want to save myself some pain if there's no point.

**Comment by mattisking** [comment]
Yup, works just fine.

**Comment by krishankumar95** [comment]
Can be referred to confirm Rancher Desktop as a pre-req alternative of Docker Desktop.
