### ISSUE TITLE
Connect to Azure Service Bus Emulator via Service Bus Explorer

### ISSUE THREAD

**Issue by MuhamedKr** [Azure/azure-service-bus-emulator-installer#34]
Is there a way to connect to Azure Service Bus Emulator via Service Bus Explorer? 
I tried a couple of things, using connection strings provided in the brief documentation but nothing is working

**Comment by Saglodha** [comment]
@MuhamedKr - Azure Service Bus emulator isn't compatible with community owned open-source Service Bus explorer. We have mentioned it in our public documentation as well - https://learn.microsoft.com/en-us/azure/service-bus-messaging/overview-emulator#benefits
