### ISSUE TITLE
Wrong config path in docker compose sample

### ISSUE THREAD

**Issue by scrocquesel-ml150** [Azure/azure-service-bus-emulator-installer#39]
The path is wrong here
https://github.com/Azure/azure-service-bus-emulator-installer/blob/13bbcffc9afc3424b56016b70a1618d825d2e9d5/Docker-Compose-Template/docker-compose-with-containerized-app.yml#L7

Should be `/ServiceBus_Emulator/ConfigFiles/Config.json`

**Comment by krishankumar95** [comment]
Fixed with PR #41
