### ISSUE TITLE
ServiceBus.Emulator.Console.Sample has the Vulenerable veriso of System.Text.Json

### ISSUE THREAD

**Issue by viveknuna** [Azure/azure-service-bus-emulator-installer#43]
Visual studio is complaining about the transitive vulnerability in one of the packages. This should be fixed.

![Image](https://github.com/user-attachments/assets/3ce90ea1-215f-4042-a3b3-472cd3739eb3)

**Comment by viveknuna** [comment]
For some reason I cannot create a branch, so please add the below line to the https://github.com/Azure/azure-service-bus-emulator-installer/blob/main/Sample-Code-Snippets/NET/ServiceBus.Emulator.Console.Sample/ServiceBus.Emulator.Console.Sample/ServiceBus.Emulator.Console.Sample.csproj

<PackageReference Include="System.Text.Json" Version="9.0.0" />

**Comment by krishankumar95** [comment]
@viveknuna ; You can contribute by forking the repo and then raising a PR.

**Comment by krishankumar95** [comment]
Resolved with PR #44
